name: discovering-disease-outbreaks
channels:
  - conda-forge
dependencies:
  - python=3.10
  - python_abi=3.10
  - pandas=2.2.2
  - numpy=1.26.4
  - scikit-learn=1.5.1
  - basemap=1.4.1
  - black=24.8.0
  - matplotlib=3.8
  - matplotlib-base=3.8
  - seaborn=0.13.2
  - unidecode=1.3.8
  - pip=24.2
  - pillow=10.4.0
  - jupyter=1.0.0
  - jupyter_contrib_nbextensions=0.5.1
  - nbconvert=7.16.4
  - pip:
      - geonamescache==2.0.0
